sudo: false
language: rust

rust:
  - stable
  - beta

addons:
  apt:
    packages:
    - cabal-install-1.24
    - ghc-8.0.2

cache:
  cargo: true
  directories:
    - $HOME/.cabal/packages
    - $HOME/.cabal/store
    - $HOME/.cabal/bin

# See: https://github.com/haskell/cabal/blob/master/.travis.yml
before_cache:
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index*
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index*
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/*.json

before_script:
  - export PATH=$PATH:$HOME/.cabal/bin
  - cabal install pandoc
  - export PATH=$PATH:$HOME/.cargo/bin
  - cargo install rustfmt || true

script:
  - cargo clean
  - cargo fmt -- --write-mode=diff
  - cargo build
  - cargo test
  - cargo run --example definition
