sudo: true
distro: xenial
language: rust

rust:
  - stable
  - beta

cache:
  cargo: true

before_script:
  - wget https://github.com/jgm/pandoc/releases/download/2.9.2.1/pandoc-2.9.2.1-1-amd64.deb
  - sudo dpkg -i pandoc-2.9.2.1-1-amd64.deb
  - rustup component add rustfmt

script:
  - cargo clean
  - cargo fmt -- --check
  - cargo build
  - cargo test
  - cargo run --example definition
