sudo: false
language: rust
cache: cargo

rust:
  - stable
  - beta

addons:
  apt:
    packages:
    - cabal-install-1.24
    - ghc-8.0.2

before_script:
  - export PATH=$PATH:$HOME/.cabal/bin
  - cabal install pandoc
  - export PATH=$PATH:$HOME/.cargo/bin
  - cargo install rustfmt || true

script:
  - cargo clean
  - cargo fmt -- --write-mode=diff
  - cargo build
  - cargo test
  - cargo run --example definition
