sudo: false
language: rust

rust:
  - stable
  - beta

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - cabal-install-1.24
      - ghc-8.0.2

cache:
  cargo: true
  directories:
    - $HOME/.cabal/packages
    - $HOME/.cabal/store
    - $HOME/.cabal/bin

# See: https://github.com/haskell/cabal/blob/master/.travis.yml
before_cache:
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index*
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index*
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/*.json

before_script:
  - export PATH=/opt/ghc/8.0.2/bin:/opt/cabal/1.24/bin:$PATH
  - export PATH=$PATH:$HOME/.cabal/bin
  - cabal update
  - cabal install pandoc
  - export PATH=$PATH:$HOME/.cargo/bin
  - rustup toolchain install nightly
  - rustup component add --toolchain nightly rustfmt-preview
  - which rustfmt || cargo install --force rustfmt-nightly

script:
  - cargo clean
  - cargo +nightly fmt -- --write-mode=diff
  - cargo build
  - cargo test
  - cargo run --example definition
